[project]
name = "ada-hackaton-team-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "angelAlk", email = "angel.alcantara@nubank.com.mx" }
]
requires-python = ">=3.14"
dependencies = [
    "joblib>=1.6.0",
    "pandas",
    "pyarrow",
    "scikit-learn>=1.9.0",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["."]

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
