[project]
name = "ada-hackaton-team-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "angelAlk", email = "angel.alcantara@nubank.com.mx" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas",
    "pyarrow",
]

[tool.uv]
package = false
